# ============================================================================
# Config file for RevComp pipeline
# ==========================================[ Sections for the users ]========
#
# One of input_directory, input_pattern and input_samples must be provided
# If input_directory provided, use it otherwise if input_pattern provided,
# use it, otherwise use input_samples.
# ============================================================================


input_directory: ''
input_readtag: _R[12]_
input_pattern: '*.fastq.gz'


##############################################################################
# Revcomp section
#
# :Parameters:
#
revcomp:

    options: ''
    threads: 4


##############################################################################
#
onsuccess:
    toclean: " slurm*out fastqc.rules config.yaml .snakemake stats.txt "
